export const projectObj = {
	id: 'details',
	LightBg: false,
	lighttext: true,
	lightTextDesc: true,
	topLine: 'Teamwork = making the dream work',
	headline: 'Collaboration',
	shortDescription: 'Fostering synergy, enabling diverse expertise to converge towards shared goals',
	description: `Working alongside a small team of developers to manage and update over 30 websites, while also collaborating closely with marketing leadership, was a dynamic and multifaceted endeavor. Together, we navigated the complexities of website maintenance, seamlessly integrating design updates, implementing new features, and optimizing performance across a diverse portfolio of digital platforms. My collaborative approach has fostered a synergy between development and marketing objectives, ensuring that each website not only meets technical standards but also aligns with strategic marketing goals and user experience objectives.`,
	link: 'https://www.swansonvineyards.com/',
	buttonLabel: 'Back',
	path: '/details',
	imgStart: false,
	img: require('../../images/colab.png').default,
	alt: 'look in the mirror',
	dark: true,
	primary: true,
	darkText: false,
};

export const projectObj2 = {
	id: 'details2',
	LightBg: false,
	lighttext: true,
	lightTextDesc: true,
	topLine: 'Keeping the user engaged and satisfied',
	headline: 'UI and UX',
	shortDescription: 'Striving for effortless user flow and satisfaction',
	description: `At Vintage Wine Estates my aim was to craft a stellar user experience. There I learned that stellar experience relies on a delicate balance between web performance and site design. Prioritizing web performance involves optimizing loading times, minimizing latency, and ensuring smooth functionality across devices, all of which contribute to a seamless browsing experience. Meanwhile, thoughtful site design incorporates intuitive navigation, visually appealing layouts, and engaging interfaces to captivate users and keep them engaged. By seamlessly integrating these elements, businesses can foster user satisfaction, encourage exploration, and ultimately, drive conversion rates and brand loyalty.`,
	buttonLabel: 'Back',
	link: 'https://www.cherrypiewines.com/',
	path: '/details2',
	imgStart: false,
	img: require('../../images/UI-UX.png').default,
	alt: 'Cherry Pie wines website',
	dark: true,
	primary: true,
	darkText: false,
};

export const projectObj3 = {
	id: 'details3',
	LightBg: false,
	lighttext: true,
	lightTextDesc: true,
	topLine: 'A Swiss Army knife in the toolkit of life',
	headline: 'Adaptability',
	shortDescription: 'The art of thriving in the face of change, turning challenges into stepping stones for progress.',
	description: `Rapidly mastering Coresense, a web-based e-commerce platform, and Smarty templates, a PHP-based templating system, while drawing from an established code base has facilitated the creation of an efficient workflow characterized by adaptability and agility. By swiftly familiarizing myself with these technologies, I've seamlessly integrated new features and functionalities into existing frameworks, ensuring a smooth transition and consistent development pace. This high level of adaptability has enabled me to respond swiftly to evolving project requirements, iterate efficiently, and deliver optimal solutions that meet both business objectives and user needs.`,
	buttonLabel: 'Back',
	link: 'https://www.windsorvineyards.com/',
	path: '/details3',
	imgStart: false,
	img: require('../../images/adaptability.png').default,
	alt: 'windsor vineyards website',
	dark: true,
	primary: true,
	darkText: false,
};

export const projectObj4 = {
	id: 'details4',
	LightBg: false,
	lighttext: true,
	lightTextDesc: true,
	topLine: 'Effortless site navigation for all!',
	headline: "Accessibilty",
	shortDescription: 'Promoting inclusivity and equal opportunities in the digital realm.',
	description: `My endeavor to enhance web accessibility across all Vintage Wine Estates websites underscores a commitment to inclusivity and user-centric design. Leveraging tools like Lighthouse and Axe, I meticulously evaluated each website's components, ensuring compliance with accessibility standards. By scrutinizing factors such as navigation, color contrast, and interactive elements, potential barriers for users with disabilities were identified and addressed. Implementing measures like descriptive alt text for images, keyboard navigation enhancements, and semantic HTML markup ensures a more seamless experience for all visitors. My dedication to improving web accessibility not only aligns with ethical principles but also strengthened Vintage Wine Estates' brand reputation, demonstrating a genuine commitment to serving diverse audiences.`,
	buttonLabel: 'Back',
	link: 'https://shop.acecider.com/',
	path: '/details4',
	imgStart: false,
	img: require('../../images/cream-accessibility.png').default,
	alt: 'look in the mirror',
	dark: true,
	primary: true,
	darkText: false,
};